services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backoffice_backend
    ports:
      - "127.0.0.1:8085:8000"
    environment:
      - USE_TEST_MODE=false
      - AZURE_CLIENT_ID=1be92fb6-e237-4bd6-ae1e-f2c4644d1766
      - AZURE_TENANT_ID=534253fc-dfb6-462f-b5ca-cbe81939f5ee
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: backoffice_frontend
    ports:
      - "127.0.0.1:8084:80"
    depends_on:
      - backend
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: backoffice_node_exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    restart: always